title: Blip - Tools of Mass Imagination
description: Empowering visual art creators with the ability to create games with AI on the phone.
url: https://blip.game
baseurl: ""

# Build settings
markdown: kramdown
permalink: "/:title"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Include elements 
# (dot-names are excluded by default)
include:
  - .well-known

# Exclude from processing
exclude:
  - Dockerfile
  - docker-test.sh
  - .git/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - vendor/
  - node_modules/
  - README.md